//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeAnywhere.StorageProviders.Azure {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeeAnywhere.StorageProviders.Azure.AzureResources", typeof(AzureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure Blob Account ähnelt.
        /// </summary>
        internal static string Configuration_Name_Blob {
            get {
                return ResourceManager.GetString("Configuration_Name_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure File Account ähnelt.
        /// </summary>
        internal static string Configuration_Name_File {
            get {
                return ResourceManager.GetString("Configuration_Name_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter Account Name and Access Token. ähnelt.
        /// </summary>
        internal static string Form_Test_Credentials_Required {
            get {
                return ResourceManager.GetString("Form_Test_Credentials_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection failed! ähnelt.
        /// </summary>
        internal static string Form_Test_Failed {
            get {
                return ResourceManager.GetString("Form_Test_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection succeeded. ähnelt.
        /// </summary>
        internal static string Form_Test_Succeeded {
            get {
                return ResourceManager.GetString("Form_Test_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testing Connection... ähnelt.
        /// </summary>
        internal static string Form_Test_Testing_Connection {
            get {
                return ResourceManager.GetString("Form_Test_Testing_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure Blob Storage Account Configuration ähnelt.
        /// </summary>
        internal static string Form_Title_Blob {
            get {
                return ResourceManager.GetString("Form_Title_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azure File Storage Account Configuration ähnelt.
        /// </summary>
        internal static string Form_Title_File {
            get {
                return ResourceManager.GetString("Form_Title_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your Azure credentials here. ähnelt.
        /// </summary>
        internal static string Keepass_Banner_Line {
            get {
                return ResourceManager.GetString("Keepass_Banner_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorize to Azure ähnelt.
        /// </summary>
        internal static string Keepass_Banner_Title {
            get {
                return ResourceManager.GetString("Keepass_Banner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blob Path ähnelt.
        /// </summary>
        internal static string Label_Item_Name_Blob {
            get {
                return ResourceManager.GetString("Label_Item_Name_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Path ähnelt.
        /// </summary>
        internal static string Label_Item_Name_File {
            get {
                return ResourceManager.GetString("Label_Item_Name_File", resourceCulture);
            }
        }
    }
}
